//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloon.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrderList
    {
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string Title { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
