//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloon.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ServicList
    {
        public string Service { get; set; }
        public string Categoru { get; set; }
        public int Cost { get; set; }
        public int Duration { get; set; }
    }
}
